07/02/23 v4.2.0 Commit
Use Unity 2022.3.4f1 to open this project.  Uses XRIT 2.4.0

07/02/23 v4.2.0 Commit
* Converted project from 2021.3.11.f1 using XRIT 2.4.0 from 2021.3.11f1 using XRIT 2.3.2.
* Fixed a bunch of issues as the result of this including issues with the URP (Universal Render Pipeline with these three errors that cropped up as a result of this conversion:

Assets\Scripts\URPScreenFade.cs(4,29): error CS0234: The type or namespace name 'Universal' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)

Assets\Scripts\URPScreenFade.cs(9,12): error CS0246: The type or namespace name 'Volume' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\URPScreenFade.cs(10,13): error CS0246: The type or namespace name 'ColorParameter' could not be found (are you missing a using directive or an assembly reference?)

* As well I ran into issues with the OVRLint.cs script on lines 842 and 844, due to a deprecated property:

Assets\Oculus\VR\Editor\OVRLint.cs(842,29): error CS1061: 'AudioImporter' does not contain a definition for 'SampleSettings' and no accessible extension method 'SampleSettings' accepting a first argument of type 'AudioImporter' could be found (are you missing a using directive or an assembly reference?)

Assets\Oculus\VR\Editor\OVRLint.cs(844,15): error CS1061: 'AudioImporter' does not contain a definition for 'SampleSettings' and no accessible extension method 'SampleSettings' accepting a first argument of type 'AudioImporter' could be found (are you missing a using directive or an assembly reference?)

The solution was to replace that method with this updated one, replacing the old SetAudioPreload with the new property AudioImporter.preloadAudioData as well as replacing importer.preloadAudioData with sampleSettings.loadType == AudioClipLoadType.DecompressOnLoad on line 842 and replacing  importer.preloadAudioData with importer.defaultSampleSettings = sampleSettings on line 844 and wrapping the comparison sampleSettings.loadType == AudioClipLoadType.DecompressOnLoad within parentheses to ensure it is evaluated before the comparison with preload.

static void SetAudioPreload(AudioClip clip, bool preload, bool refreshImmediately)
{
    if (clip != null)
    {
        string assetPath = AssetDatabase.GetAssetPath(clip);
        AudioImporter importer = AssetImporter.GetAtPath(assetPath) as AudioImporter;
        if (importer != null)
        {
            AudioImporterSampleSettings sampleSettings = importer.defaultSampleSettings;
            if (preload != (sampleSettings.loadType == AudioClipLoadType.DecompressOnLoad))
            {
                sampleSettings.loadType = preload ? AudioClipLoadType.DecompressOnLoad : AudioClipLoadType.CompressedInMemory;
                importer.defaultSampleSettings = sampleSettings;

                AssetDatabase.ImportAsset(assetPath);
                if (refreshImmediately)
                {
                    AssetDatabase.Refresh();
                }
            }
        }
    }
}

* My project then crashed upon converting/loading/importing assets.  Through successfully converting a copy of the Create With Unity 2021 starter pack to version 2022.3.4f1 with XRIT 2.4.0.

Then through trial and error loading assets from the asset folder incrementally into Assets folder until the project was able to be opened in Safe Mode without crashing, I was able to see both the compile errors in the Console window as well as a message in the Console window that showed that Unity had crashed while importing in the assets from my "This is Fine" meme.

After resolving the compile errors (above) and by removing/not having that folder in my Assets folder I was able to launch the project but I noticed that all of the imported Question Hound/This is Fine meme assets from Thingiverse were missing and that only my colored veneer Unity 3D shape game objects remained.

This means the converted OBJ files were what was causing the crash.  I confirmed this by copying everything but the OBJ files and discovering that the project still launched OK without crashing.

I then tried re-downloading the STLs from Thingiverse and converting them again using, the first time, the same online STL to OBJ converter as before (ANYCONV https://anyconv.com/stl-to-obj-converter) but these newly converted OBJs crashed the project on load again.  So I then tried converting the STLs to OBJ using a different online converter (ASPOSE https://products.aspose.app/cad/conversion/stl-to-obj#:~:text=How%20to%20use%20STL%20converter%20app%20by%20Aspose.CAD%3F,our%20other%20apps%2C%20such%20as%3A%20...%20More%20items) but these newly converted OBJs also crashed the project on load again.

In the end I ended up downloading and installing Luzbot Cura version 3.6.37 (https://lulzbot.com/support/cura-windows) onto my D drive and I used the File menu there to open a new project, to open the STL one at a time and then to Save as as a OBJ file.  This worked.

The newly converted files were different than before and the mesh for all of the "default" game objects in my Hierarchy window, which represented the imported ANYCONV OBJs from before, were now missing.  So I had to Alt + click expand the entire This is Fine meme, I needed to find the default game objects and I needed to drag the newly imported Lulzbot converted OBJ file's mesh (this was a child object of each OBJ imported into the Unity via the "This is Fine Dog Meme" subfolder under the "Assets" folder in my Unity project) into the Mesh field with the missing mesh.

I then went into an old version of my project, I made that meme's parent a prefab and I exported this as a package with hopes that I could import this, fix the meshes but keep all the transforms from the old project to save some time.  But despite removing the offending OBJs that caused the scene to crash and replacing them with new copies from the Lulzbot conversion, when importing all the transforms were way off and things were floating in various X, Y and Z positions from where they should be.

I then had to move all the objects to make this one cohesive collection of game objects and so that the models were again inside the veneer colored Unity shape game objects.  I tried copying component and pasting but I discovered the Paste Component Values doesn't paste across two different open Unity projects (only within the same project -- even though the paste transform was for the equivalent game object in the converted project).  So I ended up manually copying the X, Y and Z transform across when different in my new proeject from the old.

But I quickly discovered that objects were still not in the correct place, despite the X, Y and Z positional transforms matching the old project's X, Y and Z transform position to a t, so I abandoned trying to use the old transforms to move these into place and I manually moved these in to place, using the visuals from the old project as a guide, instead.

After I got everything into place I play tested and confirmed that the This is Fine meme showed up, looked to be in the correct position outside the window, that the smoke and fire looked to be in an OK positon to the Question Hound, table and base and that the smoke particle effect was working as expected.

* I also saw the Luzbot octopus in the Luzbot Cura software so, for fun, I converted this to a OBJ and brought this into my project as well.  It came in huge, which made me laugh, so I kept it the original size, I gave it its own darkish green material and I rotated and positioned it so that it's tenticles were around two of the buildings outside the west building.  It looks massive and intimidating, despite being my grandchild.

* I also had to fix the items on the North wall, which were clipping through the wall (TV, trash bin and target).

* I had to fix the two Unity provided video .mp4 video files as well as my two imported .mp4 video files by replacing these with copies from my old project.

* The hinges are working correctly now on the fireplace and the pivot point is no longer in the center of that glass (which is why I couldn't hinge and open the fireplace door before).  The pivot point is now somehow to the left, as it should be again, despite my not having fixed this.

* The collider was causing this to start partially open and when I tried to open this further to collapse and not fully hinge. To fix this I did the following

	- I added a handle that uses a fix joint and a XR Grab Interactable so that I had another point to grab onto.

	- I adjusted the box collider of the door to not be so thick on the Z axis.  But I found that the box collider was colliding with the mesh collider of the main body of the fireplace, causing this to spin, twist, fly and break windows (resetting the room at the same time).

	- The door is curved and a box collider is square so I swapped the box collider out for a convex mesh collider to more closely match the curved shape.  The box collider was hard to shape around the door and not have that collision.

	- I also set the fireplace door to the Door layer while the rest of the fireplace was already set to the Furniture layer.  Quickly checking the physics matrix I could see that the Door layer was one of the few layers that is set to not interact with Furniture layer, which is what I ultimately needed to prevent collisions.

I tested this in my Quest 2 VR headset and everything is working perfectly now.  I can open and close the fireplace door completely.  Maybe now I can add the smore toasting/melting/burning mechanic that one of my students suggested to me.

* I play tested everything again.  The blue chest is still hinged and it's hinge closes over time (which was unintentional but a nice realistic touch).

* The trap door floor is of course not included in this project but I'm not sure that I'll prusue adding this feature right away -- and if I do I'd rather do it by modifying the mesh in Blender rather than piecing together multiple floors to make a hole.

* Also, in that testing there was still a collider in place over the hole, despite my disabling everything I could think of that had a collider on it and checking this multiple times using the Unity Gizmos showing just the colliders. I could see no collider over this hole I made, despite the fact that I could stand on it and not fall through the hole.  So it wasn't working perfectly anyway.

* The polaroid camera's spawn point was too far forward again so I fixed this.

	- There is still the glitch that happens when picking up the photos from the end of the camera.  The hand collisions turn back on which causes the camera to spin or be pushed in unusual ways. I may need to turn off collisions again specifically when dropping the photos.  The problem is I need to differentiate between dropping the photos while still holding the camera and when not as there will be a different bug introduced if I disable hand collisions every time a photo is dropped.  But I haven't decided on the best way to do this yet.
	- Those photos also still have traditional grab interactable and not the Jedi Force Pull script (a custom XR Grab Interactable script) as that script was causing all sorts of issues with how the photos reacted when being instantated from the camera.  Some day I'll revisit this to see if I can troubleshoot and resolve -- I needed to just have this work for my day one demo of this room in my classes and I didn't have the time to thoroughly investigate this before.

* I fixed the Dalek's shoulder which was missing a material.

* The single colldier and moving Link's wooden sword up slightly so it doesn't clip through the floor and fall into the void when picked up was no longer there so I added and sized a single box collider at the top level.  I then made sure the bottom of the collider was just above the floor in isometric mode so that there is no chance of this falling through the floor collider.

* All the videos, window breaking, the breakable laptop, the dart gun, the flashlight, the Dalek audio playing, the remote, the game contollers, the book sockets, the Alyx cube flicking mechanic, the whiteboard and eraser and whiteboard UI to change the marker color, the wax fruit, the two notebooks, the magnifying glass, and the stapler, the clock, the eating mechanic items, the holographic watch and it's UI buttons, the hats, the lighter and candles as well as the lighting the rung on fire with the candle or lighter, opening the blue chest, picking up the sports items in the blue chest the mirror, the door and the portal/scene change to the Peaceful Nowhere, etc. all seem to be in great shape and working correctly.

* I started the copy of all the corrupt and test projects to the E drive of my gaming computer to keep this folder neat.

* I updated the version number and date on the Welcome Board and I also added the Unity Editor version below that.

* Up next fix the following:
	- The polaroid camera
	- The target mini game is a mess and needs to be fixed
	- Figure out the best way to differentiate between dropping the photos while holding onto the camera vs. not so that I can disable the colliders during the former but not the later.
	- Figure out how to get the Jedi Force Pull to work with the photos but not break anything else.
	- Add marshmallow roasting mechanic to fire.
	- Figure out the trap door collision issue as well as how to best modify the mesh (add a hole) in Blender.

* That's it for tonight.
@mattdway mattdway committed on July 2